title: "Pierre Roudier's blog"
description: "Linux Environments and Java Technologies"
motto: "Linux Environments and Java Technologies"

url: "https://roudier.io"
baseurl: ""

twitter_username: proudier
github_username:  proudier
linkedin_username: pierreroudier

markdown: kramdown
theme: alpha-one

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-minifier

permalink: /:year-:month-:day/:title

pagination:
  enabled: true
  per_page: 6
  indexpage: 'posts'
  permalink: 'posts_:num.html'
  trail:
    before: 3
    after: 3


header_link_1_label: Posts
header_link_1_href: posts.html

favicon_png: favicon.png

exclude:
  - wp-mig.sh