title: "Pierre Roudier's blog"
description: "Linux Environments and Java Technologies"
motto: "Linux Environments and Java Technologies"
author: "Pierre Roudier"
url: "https://roudier.io"
baseurl: ""

twitter_username: proudier
github_username:  proudier
linkedin_username: pierreroudier

markdown: kramdown
theme: alpha-one

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-minifier
  - jekyll-sitemap

permalink: /:year/:month/:title/

pagination:
  enabled: true
  per_page: 6
  indexpage: 'posts'
  permalink: 'posts:num.html'
  trail:
    before: 3
    after: 3


header_link_1_label: 'All posts'
header_link_1_href: posts/posts.html

favicon_png: favicon.png

exclude:
  - wp-mig.sh
  - .idea
  - .gitignore
  - publish.sh